trigger:
- main

pool:
  name: Default
  # or your pool name where your self-hosted agent is

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '16.x'  # Node.js version
  displayName: 'Install Node.js'

- script: |
    npm install -g http-server
  displayName: 'Install http-server'

- script: |
    dir
  displayName: 'Prepare static site (Windows)'

# Optional: You can add a Publish build artifact step
- publish: $(Build.SourcesDirectory)
  artifact: static-site
  displayName: 'Publish static site artifact'
